### ISSUE TITLE
Cant install monterey.

### ISSUE THREAD

**Issue by MrTheShy** [herrnst/HuaweiMatebookD14AMD-OpenCore#1]
I can't install Monterey because the installation process freezes at 12 minutes remaining.
Another strange problem is that I can only successfully format in HFS Plus journaled.
I can't format directly to apfs, but when I start the installation process and select the hfs drive as the disk to install macOS on, it converts to apfs (using disk utility to convert from hfs to apfs doesn't work).
PC freezes completely at 12 minutes remaining, in logs I see 
"osinstallersetupd[427]: Unable to verify trust (5) using MobileSoftwareUpdate policy. Will try basic X509"
Any help? I have the same MateBook, same everything, except it doesn't work.
I'm trying to dual boot with Windows, I can't lose the Windows partition and can't even back it up anywhere.
When the laptop freezes first the monitor goes off black, but I can see the USB LED still going on, the PC is on and the OS is reading from the disk, after 3/5 minutes it goes off and the installation is not complete.

**Comment by herrnst** [comment]
I actually didn't try Monterey so I'm afraid I cannot really help in this regard. If you're running the installer with NootedRed enabled, you should really disable the Kext during the installation process (and also during any software update from within the installed system) as I found out this causes installer issues including hangs some time into the installation.

**Comment by MrTheShy** [comment]
i found out the problem, the stock ssd is incompatible

**Comment by herrnst** [comment]
Shouldn't that be handled by NVMeFix.kext?

**Comment by MrTheShy** [comment]
it should, right, but for some ssd types i think it's just impossible

**Comment by herrnst** [comment]
Hm, interesting. Guess I'll put a warning into the README regarding the PM981 as someone else contacted me by other means with issues regarding the SSD. As mentioned in the README, I replaced the NVMe with a WD_BLACK one prior to "finally" installing macOS, so can't really tell how it goes.

**Comment by herrnst** [comment]
README updated with a note about possible problems with the PM981, nothing that can be fixed in the context of the OpenCore configuration.
