### ISSUE TITLE
Bluetooth not working with AX210 on the Matebook D16

### ISSUE THREAD

**Issue by moesture** [herrnst/HuaweiMatebookD14AMD-OpenCore#2]
Hi. I understand this repo is for D14, but I was hoping you might still be able to help me.

Wifi is working.
<img width="456" alt="image" src="https://github.com/herrnst/HuaweiMatebookD14AMD-OpenCore/assets/3960822/6dd3b47b-0b84-4094-ba46-5a4cfbea8d34">

but bluetooth is not.
<img width="456" alt="image" src="https://github.com/herrnst/HuaweiMatebookD14AMD-OpenCore/assets/3960822/44944799-d99a-4fba-b001-721ade4eb3c9">

Can't find any information about BT in the USB section.
<img width="543" alt="image" src="https://github.com/herrnst/HuaweiMatebookD14AMD-OpenCore/assets/3960822/46ed0cdc-01db-43f4-bb57-96c98d0d2324">
 
Is this relevant to USB mapping?

OS: Ventura 13.6.5
HW: Matebook 16 2020 with CPU R5-5600H

**Comment by herrnst** [comment]
No idea really, If it works in other OSes and you have https://github.com/OpenIntelWireless/IntelBluetoothFirmware and BlueToolFixup from https://github.com/acidanthera/BrcmPatchRAM in place, then maybe retry doing the USBMap stuff and just map all available USB ports.

**Comment by moesture** [comment]
Problem solved. I had previsouly disabled the BT in BIOS when using the usb BT dongle and forget to and turn it back on. Additionally, I needed to remove the IntelBluetoothInjector from kexts.
Thank you for your time :)
