### ISSUE TITLE
Brightness not working properly

### ISSUE THREAD

**Issue by macsanity** [herrnst/HuaweiMatebookD14AMD-OpenCore#3]
If you cold boot your machine brightness will not work, but in my case since I have dual boot windows and mac, if you boot on windows and do a reboot and boot to macos brightness will work properly.

**Comment by herrnst** [comment]
https://github.com/ChefKissInc/NootedRed/issues/236

**Comment by macsanity** [comment]
> [ChefKissInc/NootedRed#236](https://github.com/ChefKissInc/NootedRed/issues/236)

I thought it was working on your end since it's not indicated in your github😥

**Comment by herrnst** [comment]
TBH I don't care very much about the macOS install on the D14 as I don't really use it at all (I prefer running Linux on the device) as macOS right now runs rather sluggish, keeps the fan running and sucks up the battery, and I tried quite a few things and didn't find a real solution for these things, though from inside macOS (ie. via IORegistryExplorer and SMC monitoring tools) everything looks quite well. Re the brightness controls, I initially had it set to a comfortable level, then things broke with some NootedRed update but it still gets set properly when the login screen appears. But as initially mentioned I don't really care right now, just keeping Kexts updated for now but am not using the macOS install at all.
